### PR TITLE
Update version to 1.11.0.0

### PR DESCRIPTION
**Pull request by lezzago**
*Issue #, if available:*

*Description of changes:*
Added release notes for 1.11.0.0 and bumped version to 1.11.0.0

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ftianli-amzn** [comment]
Glad to see so many new changes in this release. 🙌 😁

**Review by ftianli-amzn — APPROVED** [review]
Glad to see so many new changes in this release. 🙌 😁

**Comment by skkosuri-amzn** [comment]
Could you change the common-utils to 1.11.0.0

**Comment by lezzago** [comment]
> Could you change the common-utils to 1.11.0.0

In the code, its set by the `opendistroVersion`

`compile "com.amazon.opendistroforelasticsearch:common-utils:${opendistroVersion}.0"`
[code link](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/core/build.gradle#L28)

**Review by skkosuri-amzn — APPROVED** [review]

**Pull request merged**
