### PR TITLE
Porting CVE fixes to 1.13

### PR DESCRIPTION
**Pull request by AWSHurneyt**
*Issue #, if available:*

*Description of changes:*
1. Updating dependencies based on PRs #393  and #395.
2. Fixing `ktlint` errors.

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by lezzago — DISMISSED** [review]

**Review by qreshi — DISMISSED** [review]

**Comment by peterzhuamazon** [comment]
Hi @CEHENKLE @bbarani I enabled the actions of this repo for @lezzago to run checks.
Once completed @lezzago should let me know so I can disable the actions again.

Thanks.

**Comment by lezzago** [comment]
@peterzhuamazon can you please disable the "Build Alerting with JDK 12" check. That check is not needed as we are buying it with JDK 14 only now

**Comment by peterzhuamazon** [comment]
@lezzago I have removed the requirement of this test.
Thanks.

**Review by lezzago — DISMISSED** [review]

**Comment by peterzhuamazon** [comment]
Disable actions again as all the checks passed and no need to run actions anymore.
Thanks.

**Review by lezzago — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
To confirm, these changes successfully built locally.

**Review by qreshi — APPROVED** [review]

**Pull request merged**
